### PR TITLE
Example with WiFiManager enabled and Ticker for blinking LED status

### PR DESCRIPTION
**Pull request by mili-tar**
Uses library Ticker.

[WiFiSPIESP.zip](https://github.com/JiriBilek/WiFiSpiESP/files/2840181/WiFiSPIESP.zip)

### CODE REVIEW

**Comment by JiriBilek** [comment]
Hi, 
thanks, but I have problems with the PR.
Changing base to dev-0.2 as the base dev-0.2.0 is now obsolete.

**Comment by JAndrassy** [comment]
Jiri,, this PR doesn't contain any new commit, only your commits which are differences between branches. mili-tar put the changes into attached zip

**Comment by JiriBilek** [comment]
I see, but made a mess with branches somehow with renaming and rebasing. I have to sort it out before modifying and committing the WiFiSPIESP.ino file. And I want to test the changes before committing :)
I will return to it tomorrow, I hope

**Comment by mili-tar** [comment]
Sorry, it's my first time in GitHub.
I really did not understand clearly how to do the pull request, so I try to start off the master.

**Comment by JiriBilek** [comment]
After some difficulties (not being a github guru either), I reworked your proposal into https://github.com/JiriBilek/WiFiSpiESP/pull/12 and merged it.
I changed:
- idle interval 1.5 sec into 1 second;
- after connecting the LED is switched OFF (instead of ON).

Thank you for your contribution.

**Pull request merged**
