### PR TITLE
OTA AVR ISP (optional)

### PR DESCRIPTION
**Pull request by JAndrassy**
I [discovered](http://forum.arduino.cc/index.php?topic=524853.msg3579696) your WiFi SPI system for esp8266 3 days ago. In my free time I maintain WiFi Link and I was working on OTA AVR ISP support. But in WiFi Link it is complicated.
In your firmware the integration of OTA upload was easy, once I had the SPISlave.end() ready.
For SPISlave library I have a pull request with SPISlave.end(). In your firmware I added it to spi slave source files.
Everything in this pull request is a clean addition and optional with a `#define`. The code added in loop() is copied from AVRISP example with two lines added: the SPISlave.end() and ESP.reset().

### CODE REVIEW

**Comment by JiriBilek** [comment]
Hi, thanks for the improvement. As I have virtually no experience with OTA upload, I have a question:
How does it work? Is it that on start, the ESP8266 checks if there is an update (delivered over a wifi connection) and before establishing the SPI (slave) connection with the Arduino loads new firmware via SPI line?
If it is so, how is the ESP connected to the internet on start? Is it ESP8266mDNS what does the magic?

**Comment by JAndrassy** [comment]
AVR ISP lib starts a server on port 328. It listens for avrdude network upload all the time. The mdns propagates the info about ota upload availability. You can list mdns on linux with command `avahi-browse -alr`.
In [README.MD](https://github.com/jandrassy/WiFiSpiESP#optional-ota-avr-isp) I added a chapter. 
[WiFiManager](https://github.com/tzapu/WiFiManager) inside `#ifdef` handles the WiFi connection on start.

**Comment by JiriBilek** [comment]
Thanks it looks great. 
Now, I have to test stability with `WiFi.persistent(false);` removed. I used to have serious problems without it.

**Comment by JAndrassy** [comment]
I didn't remove the disconnect. it is only in #ifNdef. 

I think it is possible to accept the pull request into new branch, if you do not want it in master for now.

**Comment by JiriBilek** [comment]
I meant that when the **#ifndef** (OTA functionality) is active, it might affect the stability of the app. I wrote the code nearly a year ago and now I can't remember exactly how the issue with `WiFi.persistent` behaved.

Please move your PR to the other branch I've just created. It seems to me that I can't do it myself ([https://github.com/blog/2224-change-the-base-branch-of-a-pull-request](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request)). I would like to put your valuable enhancement in a separate branch for a while.

Thanks, 
Jiri

**Comment by JAndrassy** [comment]
ok. 
WiFi Manager handles and uses the persistent settings

**Comment by JiriBilek** [comment]
I quickly looked at the WiFiManager library. I'll try it first.
I want the app to be completely manageable from the master (Arduino or whatever SPI machine). I like the idea the standard user would not have to know anything about ESP (except how to reflash it from the Arduino IDE).

**Comment by JAndrassy** [comment]
I understand your concept and goal. Only there is no compromise with OTA upload in this, I think. That is why the OTA AVR ISP should be a non default option.
The concept of WiFiManager is the same as for most of Iot devices and more and more users know how to handle it.
And perhaps you add the possibility of firmware OTA upload with ArduinoOTA library.
If I would use this firmware for my main project, I would add a WebServer and SPIFFS to handle my static web files and use OTA upload for SPIFFS image. (Now I use WiFi Link this way with esp8266 on Serial1).

**Pull request merged**
